#pipeline_type: "video"
##file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/cubo/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/pasta_short/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/pasta_medium/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/sala/720_30.mp4"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/modulo_ms/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/modulo/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/elefante_1/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/elefante_2/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/elefante_3/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/elefante_4/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/elefante_5/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/elefante_6/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/elefante_7/720_30.m4v"

#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/elefante_8/720_30.m4v"

#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/sala_2/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/sala_3/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/sala_4/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/quarto_1/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/pato_1/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/pato_2/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/ovelha_1/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/telefone_1/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/mesa_1/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/mesa_2/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/mesa_3/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/estatua_1/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/estatua_2/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/estatua_3/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/estatua_4/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/estatua_5/720_30.m4v"
#file_path: "/Users/felipemoran/Dropbox/Poli/TCC/datasets/estatua_6/720_30.m4v"

pipeline_type: "synthetic"
#file_path: "1"
#file_path: "2"
file_path: "3"

synthetic_config:
    noise_covariance: 5
    number_of_cameras: 2500

    case_3:
        radius: 5
        number_of_cameras: 50
        step_size: 0.5
        x_points: 5
        y_points: 5
        z_points: 4

camera_matrix: &camera_matrix [
    [765.16859169, 0.0, 379.11876567],
    [0.0, 762.38664643, 497.22086655],
    [0.0, 0.0, 1.0],
]

use_five_pt_algorithm: false
use_solve_pnp: true
use_reconstruct_tracks: true

klt:
    calculate_every_frame: true
    display_klt_debug_frames: true
    klt_debug_frames_delay: 1
    frames_to_skip: 1
    reset_period: 1
    closeness_threshold: 15
    max_features: 100

    corner_selection:
        quality_level: 0.5
        min_distance: 15
        block_size: 10

    optical_flow:
        window_size:
            width: 15
            height: 15
        max_level: 3
        criteria:
            # original: (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 10, 0.03)
            # where cv2.TERM_CRITERIA_EPS = 2 and cv2.TERM_CRITERIA_COUNT = 1
            criteria_sum: 3
            max_iter: 30
            eps: 0.003

error_calculation:
    period: 1
    window_length: 1
    online_calculation: True
    post_calculation: True

bundle_adjustment:
    tol: 1e-2
    method: "trf"
    verbose: 0
    camera_matrix: *camera_matrix

    use_with_rolling_window: false
    rolling_window:
        method: growing_step
        period: 1 # in number of processed frame
        length: 10 # number of frames in the window taking step into account
        step: 1 # step=N means taking 1 every N frames
#    rolling_window:
#        method: constant_step
#        period: 5 # in number of processed frame
#        length: 10 # number of frames in the window taking step into account
#        step: 1 # step=N means taking 1 every N frames
    use_at_end: true

five_pt_algorithm:
    min_number_of_points: 6
    essential_mat_threshold: 5
    ransac_probability: 0.999999
    refine_matches_repetitions: 1
    save_optimized_projections: false
    camera_matrix: *camera_matrix
    distance_threshold: 500

solve_pnp:
    min_number_of_points: 5
    camera_matrix: *camera_matrix
    use_epnp: true
    use_iterative_pnp: true

init:
    error_threshold: 50
    num_reconstruction_frames: 5
    num_error_calculation_frames: 5
