synthetic_case: false

camera_matrix: [
    [765.16859169, 0.0, 379.11876567],
    [0.0, 762.38664643, 497.22086655],
    [0.0, 0.0, 1.0],
  ]

use_five_pt_algorithm: true
use_solve_pnp: true
use_reconstruct_tracks: true

klt:
    frames_to_skip: 2
    reset_period: 2

    corner_selection:
        max_corners: 100
        quality_level: 0.5
        min_distance: 15
        block_size: 10

    optical_flow:
        window_size:
            width: 15
            height: 15
        max_level: 3
        criteria:
            # original: (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 10, 0.03)
            # where cv2.TERM_CRITERIA_EPS = 2 and cv2.TERM_CRITERIA_COUNT = 1
            criteria_sum: 3
            max_iter: 10
            eps: 0.003

init:
    method: five_pt_algorithm
    error_threshold: 0.2
    five_point:
        first_frame_fixed: false

five_point_algorithm:
    min_number_of_points: 6
    threshold: 5
    probability: 0.999

recover_pose_algorithm:
    distance_threshold: 50

solvepnp:
    min_number_of_points: 10

bundle_adjustment:
    use_with_first_pair: false
    use_with_rolling_window: false
    rolling_window:
        method: growing_step # constant_step or growing_step
        period: 1 # in number of processed frame
        length: 10 # number of frames in the window taking step into account
        step: 1 # step=N means taking 1 every N frames
    use_at_end: true
    verbosity: 2