from dataclasses import dataclass
from typing import Tuple, Any, List, Union
import ruamel.yaml
from ruamel.yaml.constructor import SafeConstructor
import dacite
import numpy as np


@dataclass
class CornerSelectionConfig:
    """
    Config for the corner selection phase of KLT
    """

    quality_level: float
    min_distance: int
    block_size: int


@dataclass
class OpticalFlowWindow:
    """
    Config for the feature tracking phase of KLT
    """

    width: int
    height: int


@dataclass
class OpticalFlowStopCriteria:
    """
    Stop criteria for optical flow tracking phase
    """

    criteria_sum: int
    max_iter: int
    eps: float


@dataclass
class OpticalFlowConfig:
    """
    Bundled optical flow configs
    """

    window_size: OpticalFlowWindow
    max_level: int
    criteria: OpticalFlowStopCriteria


@dataclass
class KLTConfig:
    """
    Bundled KLT config
    """

    calculate_every_frame: bool
    display_klt_debug_frames: bool
    klt_debug_frames_delay: int
    frames_to_skip: int
    reset_period: int
    closeness_threshold: int
    max_features: int

    corner_selection: CornerSelectionConfig
    optical_flow: OpticalFlowConfig


@dataclass
class RollingWindowConfig:
    """
    Configs for Bundle Adjustment's rolling window config
    """

    method: str
    period: int
    length: int
    step: int


@dataclass
class BundleAdjustmentConfig:
    """
    Configs for Bundle Adjustment module
    """

    tol: float
    method: str
    verbose: int
    camera_matrix: Any

    use_with_rolling_window: bool
    use_at_end: bool
    rolling_window: RollingWindowConfig

    def __post_init__(self):
        self.camera_matrix = np.array(self.camera_matrix)


@dataclass
class ErrorCalculationConfig:
    """
    Config for error calculation module
    """

    period: int
    window_length: int
    online_calculation: bool
    post_calculation: bool


@dataclass
class FivePointAlgorithmConfig:
    """
    Configs for reconstruction using five point algorithm
    """

    min_number_of_points: int
    essential_mat_threshold: float
    ransac_probability: float
    refine_matches_repetitions: int
    save_optimized_projections: bool
    camera_matrix: Any
    distance_threshold: float

    def __post_init__(self):
        self.camera_matrix = np.array(self.camera_matrix)


@dataclass
class SolvePnPConfig:
    """
    Config for reconstruction using PnP algorithm
    """

    min_number_of_points: int
    camera_matrix: Any
    use_epnp: bool
    use_iterative_pnp: bool

    def __post_init__(self):
        self.camera_matrix = np.array(self.camera_matrix)


@dataclass
class InitConfig:
    """
    Configs for initial reconstruction phase
    """

    error_threshold: float
    num_reconstruction_frames: int
    num_error_calculation_frames: int


@dataclass
class Case3Config:
    """
    Configs for 3rd case of synthetic points generated by the SyntheticPipeline class
    """

    radius: float
    number_of_cameras: int
    step_size: float
    x_points: int
    y_points: int
    z_points: int


@dataclass
class SyntheticConfig:
    """
    General configs for generation of synthetic points
    """

    noise_covariance: float
    number_of_cameras: int

    case_3: Case3Config


@dataclass
class VideoPipelineConfig:
    """
    Bundled configurations for Video Pipeline
    """

    pipeline_type: str
    file_path: str

    synthetic_config: SyntheticConfig

    camera_matrix: Any

    use_five_pt_algorithm: bool
    use_solve_pnp: bool
    use_reconstruct_tracks: bool

    klt: KLTConfig

    init: InitConfig

    error_calculation: ErrorCalculationConfig

    five_pt_algorithm: FivePointAlgorithmConfig
    solve_pnp: SolvePnPConfig

    bundle_adjustment: BundleAdjustmentConfig

    def __post_init__(self):
        assert (
            self.use_five_pt_algorithm or self.use_solve_pnp
        ), "At least one algorithm between fiv-pt and solvepnp must be used"

        self.camera_matrix = np.array(self.camera_matrix)


def construct_tuple(self, node):
    """
    Creates a tuple out of a sequence when parsing the YAML file
    """
    seq = self.construct_sequence(node)
    if seq:
        return tuple(seq)


SafeConstructor.add_constructor(u"!tuple", construct_tuple)


def load(file):
    """
    Loads YAML config file according to VideoPipelineConfig structure
    :param file: config file object
    :return: parsed config object
    """

    config_raw = ruamel.yaml.safe_load(file)

    config = dacite.from_dict(data=config_raw, data_class=VideoPipelineConfig)
    return config
